chartDict = {0: {'data': [{'Name': 'A', 'Value': 66},
              {'Name': 'B', 'Value': 77},
              {'Name': 'C', 'Value': 52},
              {'Name': 'D', 'Value': 32},
              {'Name': 'E', 'Value': 11}],
     'q1': 1,
     'q2': 5,
     'type': 'bar'},
 1: {'data': [{'Name': 'A', 'Value': 15},
              {'Name': 'B', 'Value': 19},
              {'Name': 'C', 'Value': 20}],
     'q1': 2,
     'q2': 1,
     'type': 'col'},
 2: {'data': [{'Name': 'A', 'Value': 15},
              {'Name': 'B', 'Value': 19},
              {'Name': 'C', 'Value': 20}],
     'q1': 2,
     'q2': 1,
     'type': 'bar'},
 3: {'data': [{'Name': 'A', 'Value': 87},
              {'Name': 'B', 'Value': 31},
              {'Name': 'C', 'Value': 52}],
     'q1': 2,
     'q2': 3,
     'type': 'col'},
 4: {'data': [{'Name': 'A', 'Value': 87},
              {'Name': 'B', 'Value': 31},
              {'Name': 'C', 'Value': 52}],
     'q1': 2,
     'q2': 3,
     'type': 'bar'},
 5: {'data': [{'Name': 'A', 'Value': 64},
              {'Name': 'B', 'Value': 37},
              {'Name': 'C', 'Value': 41}],
     'q1': 1,
     'q2': 2,
     'type': 'col'},
 6: {'data': [{'Name': 'A', 'Value': 64},
              {'Name': 'B', 'Value': 37},
              {'Name': 'C', 'Value': 41}],
     'q1': 1,
     'q2': 2,
     'type': 'bar'},
 7: {'data': [{'Name': 'A', 'Value': 24},
              {'Name': 'B', 'Value': 67},
              {'Name': 'C', 'Value': 20}],
     'q1': 3,
     'q2': 3,
     'type': 'col'},
 8: {'data': [{'Name': 'A', 'Value': 24},
              {'Name': 'B', 'Value': 67},
              {'Name': 'C', 'Value': 20}],
     'q1': 3,
     'q2': 3,
     'type': 'bar'},
 9: {'data': [{'Name': 'A', 'Value': 42},
              {'Name': 'B', 'Value': 97},
              {'Name': 'C', 'Value': 18},
              {'Name': 'D', 'Value': 42},
              {'Name': 'E', 'Value': 93}],
     'q1': 1,
     'q2': 4,
     'type': 'col'},
 10: {'data': [{'Name': 'A', 'Value': 42},
               {'Name': 'B', 'Value': 97},
               {'Name': 'C', 'Value': 18},
               {'Name': 'D', 'Value': 42},
               {'Name': 'E', 'Value': 93}],
      'q1': 1,
      'q2': 4,
      'type': 'bar'},
 11: {'data': [{'Name': 'A', 'Value': 7},
               {'Name': 'B', 'Value': 70},
               {'Name': 'C', 'Value': 29},
               {'Name': 'D', 'Value': 29},
               {'Name': 'E', 'Value': 22}],
      'q1': 1,
      'q2': 5,
      'type': 'col'},
 12: {'data': [{'Name': 'A', 'Value': 7},
               {'Name': 'B', 'Value': 70},
               {'Name': 'C', 'Value': 29},
               {'Name': 'D', 'Value': 29},
               {'Name': 'E', 'Value': 22}],
      'q1': 1,
      'q2': 5,
      'type': 'bar'},
 13: {'data': [{'Name': 'A', 'Value': 84},
               {'Name': 'B', 'Value': 76},
               {'Name': 'C', 'Value': 46},
               {'Name': 'D', 'Value': 14},
               {'Name': 'E', 'Value': 89}],
      'q1': 2,
      'q2': 4,
      'type': 'col'},
 14: {'data': [{'Name': 'A', 'Value': 84},
               {'Name': 'B', 'Value': 76},
               {'Name': 'C', 'Value': 46},
               {'Name': 'D', 'Value': 14},
               {'Name': 'E', 'Value': 89}],
      'q1': 2,
      'q2': 4,
      'type': 'bar'},
 15: {'data': [{'Name': 'A', 'Value': 17},
               {'Name': 'B', 'Value': 42},
               {'Name': 'C', 'Value': 56},
               {'Name': 'D', 'Value': 85},
               {'Name': 'E', 'Value': 11}],
      'q1': 2,
      'q2': 4,
      'type': 'col'},
 16: {'data': [{'Name': 'A', 'Value': 17},
               {'Name': 'B', 'Value': 42},
               {'Name': 'C', 'Value': 56},
               {'Name': 'D', 'Value': 85},
               {'Name': 'E', 'Value': 11}],
      'q1': 2,
      'q2': 4,
      'type': 'bar'},
 17: {'data': [{'Name': 'A', 'Value': 11},
               {'Name': 'B', 'Value': 15},
               {'Name': 'C', 'Value': 7},
               {'Name': 'D', 'Value': 78},
               {'Name': 'E', 'Value': 8},
               {'Name': 'F', 'Value': 10},
               {'Name': 'G', 'Value': 95},
               {'Name': 'H', 'Value': 14}],
      'q1': 3,
      'q2': 6,
      'type': 'col'},
 18: {'data': [{'Name': 'A', 'Value': 11},
               {'Name': 'B', 'Value': 15},
               {'Name': 'C', 'Value': 7},
               {'Name': 'D', 'Value': 78},
               {'Name': 'E', 'Value': 8},
               {'Name': 'F', 'Value': 10},
               {'Name': 'G', 'Value': 95},
               {'Name': 'H', 'Value': 14}],
      'q1': 3,
      'q2': 6,
      'type': 'bar'},
 19: {'data': [{'Name': 'A', 'Value': 14},
               {'Name': 'B', 'Value': 39},
               {'Name': 'C', 'Value': 58},
               {'Name': 'D', 'Value': 71},
               {'Name': 'E', 'Value': 59},
               {'Name': 'F', 'Value': 68},
               {'Name': 'G', 'Value': 60},
               {'Name': 'H', 'Value': 29}],
      'q1': 1,
      'q2': 8,
      'type': 'col'},
 20: {'data': [{'Name': 'A', 'Value': 14},
               {'Name': 'B', 'Value': 39},
               {'Name': 'C', 'Value': 58},
               {'Name': 'D', 'Value': 71},
               {'Name': 'E', 'Value': 59},
               {'Name': 'F', 'Value': 68},
               {'Name': 'G', 'Value': 60},
               {'Name': 'H', 'Value': 29}],
      'q1': 1,
      'q2': 8,
      'type': 'bar'},
 21: {'data': [{'Name': 'A', 'Value': 78},
               {'Name': 'B', 'Value': 54},
               {'Name': 'C', 'Value': 23},
               {'Name': 'D', 'Value': 82},
               {'Name': 'E', 'Value': 86},
               {'Name': 'F', 'Value': 55},
               {'Name': 'G', 'Value': 31},
               {'Name': 'H', 'Value': 71}],
      'q1': 2,
      'q2': 7,
      'type': 'col'},
 22: {'data': [{'Name': 'A', 'Value': 78},
               {'Name': 'B', 'Value': 54},
               {'Name': 'C', 'Value': 23},
               {'Name': 'D', 'Value': 82},
               {'Name': 'E', 'Value': 86},
               {'Name': 'F', 'Value': 55},
               {'Name': 'G', 'Value': 31},
               {'Name': 'H', 'Value': 71}],
      'q1': 2,
      'q2': 7,
      'type': 'bar'},
 23: {'data': [{'Name': 'A', 'Value': 59},
               {'Name': 'B', 'Value': 46},
               {'Name': 'C', 'Value': 95},
               {'Name': 'D', 'Value': 14},
               {'Name': 'E', 'Value': 77},
               {'Name': 'F', 'Value': 2},
               {'Name': 'G', 'Value': 52},
               {'Name': 'H', 'Value': 93}],
      'q1': 1,
      'q2': 7,
      'type': 'col'},
 24: {'data': [{'Name': 'A', 'Value': 59},
               {'Name': 'B', 'Value': 46},
               {'Name': 'C', 'Value': 95},
               {'Name': 'D', 'Value': 14},
               {'Name': 'E', 'Value': 77},
               {'Name': 'F', 'Value': 2},
               {'Name': 'G', 'Value': 52},
               {'Name': 'H', 'Value': 93}],
      'q1': 1,
      'q2': 7,
      'type': 'bar'}}