chartDict = {0: {'data': [{'Name': 'A', 'Value': 66},
              {'Name': 'B', 'Value': 77},
              {'Name': 'C', 'Value': 52},
              {'Name': 'D', 'Value': 32},
              {'Name': 'E', 'Value': 11}],
     'q1': 1,
     'q2': 5,
     'type': 'bar'},
 1: {'data': [{'Name': 'A', 'Value': 60},
              {'Name': 'B', 'Value': 30},
              {'Name': 'C', 'Value': 66}],
     'q1': 1,
     'q2': 3,
     'type': 'col'},
 2: {'data': [{'Name': 'A', 'Value': 60},
              {'Name': 'B', 'Value': 30},
              {'Name': 'C', 'Value': 66}],
     'q1': 1,
     'q2': 3,
     'type': 'bar'},
 3: {'data': [{'Name': 'A', 'Value': 100},
              {'Name': 'B', 'Value': 32},
              {'Name': 'C', 'Value': 80}],
     'q1': 1,
     'q2': 1,
     'type': 'col'},
 4: {'data': [{'Name': 'A', 'Value': 100},
              {'Name': 'B', 'Value': 32},
              {'Name': 'C', 'Value': 80}],
     'q1': 1,
     'q2': 1,
     'type': 'bar'},
 5: {'data': [{'Name': 'A', 'Value': 87},
              {'Name': 'B', 'Value': 89},
              {'Name': 'C', 'Value': 88}],
     'q1': 1,
     'q2': 2,
     'type': 'col'},
 6: {'data': [{'Name': 'A', 'Value': 87},
              {'Name': 'B', 'Value': 89},
              {'Name': 'C', 'Value': 88}],
     'q1': 1,
     'q2': 2,
     'type': 'bar'},
 7: {'data': [{'Name': 'A', 'Value': 28},
              {'Name': 'B', 'Value': 94},
              {'Name': 'C', 'Value': 40}],
     'q1': 2,
     'q2': 3,
     'type': 'col'},
 8: {'data': [{'Name': 'A', 'Value': 28},
              {'Name': 'B', 'Value': 94},
              {'Name': 'C', 'Value': 40}],
     'q1': 2,
     'q2': 3,
     'type': 'bar'},
 9: {'data': [{'Name': 'A', 'Value': 23},
              {'Name': 'B', 'Value': 91},
              {'Name': 'C', 'Value': 57},
              {'Name': 'D', 'Value': 67},
              {'Name': 'E', 'Value': 20}],
     'q1': 2,
     'q2': 3,
     'type': 'col'},
 10: {'data': [{'Name': 'A', 'Value': 23},
               {'Name': 'B', 'Value': 91},
               {'Name': 'C', 'Value': 57},
               {'Name': 'D', 'Value': 67},
               {'Name': 'E', 'Value': 20}],
      'q1': 2,
      'q2': 3,
      'type': 'bar'},
 11: {'data': [{'Name': 'A', 'Value': 74},
               {'Name': 'B', 'Value': 57},
               {'Name': 'C', 'Value': 62},
               {'Name': 'D', 'Value': 49},
               {'Name': 'E', 'Value': 16}],
      'q1': 5,
      'q2': 4,
      'type': 'col'},
 12: {'data': [{'Name': 'A', 'Value': 74},
               {'Name': 'B', 'Value': 57},
               {'Name': 'C', 'Value': 62},
               {'Name': 'D', 'Value': 49},
               {'Name': 'E', 'Value': 16}],
      'q1': 5,
      'q2': 4,
      'type': 'bar'},
 13: {'data': [{'Name': 'A', 'Value': 75},
               {'Name': 'B', 'Value': 26},
               {'Name': 'C', 'Value': 60},
               {'Name': 'D', 'Value': 85},
               {'Name': 'E', 'Value': 44}],
      'q1': 5,
      'q2': 1,
      'type': 'col'},
 14: {'data': [{'Name': 'A', 'Value': 75},
               {'Name': 'B', 'Value': 26},
               {'Name': 'C', 'Value': 60},
               {'Name': 'D', 'Value': 85},
               {'Name': 'E', 'Value': 44}],
      'q1': 5,
      'q2': 1,
      'type': 'bar'},
 15: {'data': [{'Name': 'A', 'Value': 86},
               {'Name': 'B', 'Value': 2},
               {'Name': 'C', 'Value': 41},
               {'Name': 'D', 'Value': 79},
               {'Name': 'E', 'Value': 91}],
      'q1': 2,
      'q2': 1,
      'type': 'col'},
 16: {'data': [{'Name': 'A', 'Value': 86},
               {'Name': 'B', 'Value': 2},
               {'Name': 'C', 'Value': 41},
               {'Name': 'D', 'Value': 79},
               {'Name': 'E', 'Value': 91}],
      'q1': 2,
      'q2': 1,
      'type': 'bar'},
 17: {'data': [{'Name': 'A', 'Value': 32},
               {'Name': 'B', 'Value': 36},
               {'Name': 'C', 'Value': 68},
               {'Name': 'D', 'Value': 36},
               {'Name': 'E', 'Value': 27},
               {'Name': 'F', 'Value': 40},
               {'Name': 'G', 'Value': 2},
               {'Name': 'H', 'Value': 92}],
      'q1': 8,
      'q2': 6,
      'type': 'col'},
 18: {'data': [{'Name': 'A', 'Value': 32},
               {'Name': 'B', 'Value': 36},
               {'Name': 'C', 'Value': 68},
               {'Name': 'D', 'Value': 36},
               {'Name': 'E', 'Value': 27},
               {'Name': 'F', 'Value': 40},
               {'Name': 'G', 'Value': 2},
               {'Name': 'H', 'Value': 92}],
      'q1': 8,
      'q2': 6,
      'type': 'bar'},
 19: {'data': [{'Name': 'A', 'Value': 39},
               {'Name': 'B', 'Value': 68},
               {'Name': 'C', 'Value': 28},
               {'Name': 'D', 'Value': 53},
               {'Name': 'E', 'Value': 29},
               {'Name': 'F', 'Value': 2},
               {'Name': 'G', 'Value': 36},
               {'Name': 'H', 'Value': 32}],
      'q1': 6,
      'q2': 1,
      'type': 'col'},
 20: {'data': [{'Name': 'A', 'Value': 39},
               {'Name': 'B', 'Value': 68},
               {'Name': 'C', 'Value': 28},
               {'Name': 'D', 'Value': 53},
               {'Name': 'E', 'Value': 29},
               {'Name': 'F', 'Value': 2},
               {'Name': 'G', 'Value': 36},
               {'Name': 'H', 'Value': 32}],
      'q1': 6,
      'q2': 1,
      'type': 'bar'},
 21: {'data': [{'Name': 'A', 'Value': 59},
               {'Name': 'B', 'Value': 1},
               {'Name': 'C', 'Value': 88},
               {'Name': 'D', 'Value': 48},
               {'Name': 'E', 'Value': 5},
               {'Name': 'F', 'Value': 75},
               {'Name': 'G', 'Value': 29},
               {'Name': 'H', 'Value': 77}],
      'q1': 4,
      'q2': 6,
      'type': 'col'},
 22: {'data': [{'Name': 'A', 'Value': 59},
               {'Name': 'B', 'Value': 1},
               {'Name': 'C', 'Value': 88},
               {'Name': 'D', 'Value': 48},
               {'Name': 'E', 'Value': 5},
               {'Name': 'F', 'Value': 75},
               {'Name': 'G', 'Value': 29},
               {'Name': 'H', 'Value': 77}],
      'q1': 4,
      'q2': 6,
      'type': 'bar'},
 23: {'data': [{'Name': 'A', 'Value': 98},
               {'Name': 'B', 'Value': 18},
               {'Name': 'C', 'Value': 76},
               {'Name': 'D', 'Value': 72},
               {'Name': 'E', 'Value': 31},
               {'Name': 'F', 'Value': 14},
               {'Name': 'G', 'Value': 44},
               {'Name': 'H', 'Value': 12}],
      'q1': 6,
      'q2': 6,
      'type': 'col'},
 24: {'data': [{'Name': 'A', 'Value': 98},
               {'Name': 'B', 'Value': 18},
               {'Name': 'C', 'Value': 76},
               {'Name': 'D', 'Value': 72},
               {'Name': 'E', 'Value': 31},
               {'Name': 'F', 'Value': 14},
               {'Name': 'G', 'Value': 44},
               {'Name': 'H', 'Value': 12}],
      'q1': 6,
      'q2': 6,
      'type': 'bar'}}